"""Turn Mio's lines into Irodori-TTS jobs and the Dart index the game reads.

    python3 tools/extract_mio_lines.py > lines.json
    python3 tools/make_voice_jobs.py lines.json OUT_DIR REF_WAV > jobs.json

Each line's file is named by a hash of its text, so editing a line only
re-renders that line. Also writes lib/data/mio_voice.dart.
"""

import hashlib
import json
import sys
from pathlib import Path

APP = Path(__file__).resolve().parent.parent
VOICE = 'やわらかく温かい声の、十四歳くらいの少女。落ち着いていて、ときどき照れる。テンポよく、はきはきと話す。'
MOOD = {
    'normal': '',
    'smile': 'にこにこと嬉しそうに。',
    'proud': '得意げに、胸を張って。',
    'surprise': 'びっくりして、声を上げるように。',
    'sad': 'しょんぼりと、寂しそうに。',
    'embarrassed': '照れて、慌てたように。',
}


# How Mio should say words the model misreads. The screen keeps the
# original spelling; only what she speaks changes.
READINGS = {
    '宝物缶': 'たからものかん',
    '開かなく': 'あかなく',
    '開かない': 'あかない',
    '扉が開く': '扉があく',
    '時間を渡る': '時間をわたる',
    '142': '百四十二',
    '錆びないまま': 'さびないまま',
    'なんでぇ?!': 'なんでええ?!',
}


# Lines that need a stronger mood than their expression gives.
MOOD_OVERRIDE = {
    '持っていけない': 'しょんぼりと、悲しそうに、声を落として。',
}


def mood_for(line: dict) -> str:
    for key, mood in MOOD_OVERRIDE.items():
        if key in line['text']:
            return mood
    return MOOD.get(line['expression'], '')


def spoken(text: str) -> str:
    """What Mio actually says: no silent ellipses at either end, and
    readings applied."""
    out = text.replace('\n', '').strip().strip('…―').strip()
    for word, reading in READINGS.items():
        out = out.replace(word, reading)
    return out


def voice_id(text: str) -> str:
    key = spoken(text)
    # An overridden mood is part of the take, so it gets its own file.
    for override in MOOD_OVERRIDE:
        if override in text:
            key += '|' + MOOD_OVERRIDE[override]
    return 'mio_' + hashlib.sha1(key.encode()).hexdigest()[:10]


def main() -> None:
    lines = json.loads(Path(sys.argv[1]).read_text())
    out_dir, ref = Path(sys.argv[2]).resolve(), str(Path(sys.argv[3]).resolve())
    jobs, index = [], {}
    for line in lines:
        vid = voice_id(line['text'])
        index[line['text']] = vid
        jobs.append({
            'out': str(out_dir / f'{vid}.wav'),
            'text': spoken(line['text']),
            'caption': VOICE + mood_for(line),
            'ref': ref,
            'seed': 7,
            'duration_scale': 0.8,
        })
    json.dump(jobs, sys.stdout, ensure_ascii=False, indent=1)
    entries = '\n'.join(
        f"  {json.dumps(text, ensure_ascii=False)}: '{vid}',"
        for text, vid in index.items()
    )
    (APP / 'lib/data/mio_voice.dart').write_text(
        '// Generated by tools/make_voice_jobs.py. Do not edit by hand.\n\n'
        "/// Mio's recorded voice for each of her lines, by the line's text.\n"
        'const mioVoice = <String, String>{\n' + entries + '\n};\n'
    )


if __name__ == '__main__':
    main()
